## Import pakej yang diperlukan

In [18]:
import numpy as np
import pandas as pd
import networkx as nx

### Rangkaian contoh yang tidak berpemberat dan tidak berarah (Rajah 2.2)

In [2]:
A1=np.matrix([
  [0, 1, 1, 0, 0, 0],
  [1, 0, 1, 0, 0, 0],
  [1, 1, 0, 1, 0, 0],
  [0, 0, 1, 0, 1, 1],
  [0, 0, 0, 1, 0, 1],
  [0, 0, 0, 1, 1, 0]
])

G1=nx.from_numpy_matrix(A1)

n_G1,m_G1 = G1.order(), G1.size()

print("Bucu:", n_G1)
print("Sisi:", m_G1)

Bucu: 6
Sisi: 7


### Rangkaian contoh yang berpemberat dan tidak berarah (Rajah 2.3) 

In [3]:
A2=np.matrix([
  [0, 2, 1, 0, 0, 0],
  [2, 0, 2, 0, 0, 0],
  [1, 2, 0, 3, 0, 0],
  [0, 0, 3, 0, 4, 1],
  [0, 0, 0, 4, 0, 2],
  [0, 0, 0, 1, 2, 0]
])

G2=nx.from_numpy_matrix(A2)

n_G2,m_G2 = G2.order(), G2.size()

print("Bucu:", n_G2)
print("Sisi:", m_G2)

Bucu: 6
Sisi: 7


### Rangkaian contoh yang tidak berpemberat dan berarah (Rajah 2.5) 

In [4]:
A3=np.matrix([
  [0, 1, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0],
  [1, 0, 0, 1, 0, 0],
  [0, 0, 1, 0, 0, 1],
  [0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 1, 0]
])

G3=nx.from_numpy_matrix(A3, create_using=nx.DiGraph)


n_G3,m_G3 = G3.order(), G3.size()

print("Bucu:", n_G3)
print("Sisi:", m_G3)

Bucu: 6
Sisi: 8


### Ketumpatan rangkaian

In [5]:
#Bagi G1 (Rajah 2.2) dan G3 (Rajah 2.5)

ketumpatan_G1 = nx.density(G1)
ketumpatan_G3 = nx.density(G3)

print("Ketumpatan rangkaian Rajah 2.2:", ketumpatan_G1)
print("Ketumpatan rangkaian Rajah 2.5:", ketumpatan_G3)

Ketumpatan rangkaian Rajah 2.2: 0.4666666666666667
Ketumpatan rangkaian Rajah 2.5: 0.26666666666666666


### Darjah dan purata darjah

In [10]:
#Bagi G1 (Rajah 2.2)

darjah_G1 =  dict(G1.degree(G1.nodes()))

nx.set_node_attributes(G1, darjah_G1, 'darjah')

print("Darjah Rajah 2.2:", darjah_G1)
#output {id bucu: darjah}

Darjah Rajah 2.2: {0: 2, 1: 2, 2: 3, 3: 3, 4: 2, 5: 2}


In [13]:
#Bagi G1 (Rajah 2.2)

bil_bucu_G1 = G1.number_of_nodes()
jumlah_darjah_G1 = sum([d for n, d in G1.degree()])

purata_darjah_G1 = jumlah_darjah_G1 / float(bil_bucu_G1)

print("Purata darjah Rajah 2.2:", purata_darjah_G1)

Purata darjah Rajah 2.2: 2.3333333333333335


In [15]:
#Bagi G3 (Rajah 2.5)

darjah_masuk_G3 =  dict(G3.in_degree(G3.nodes()))

nx.set_node_attributes(G3, darjah_masuk_G3, 'darjah_masuk')

print("Darjah masuk Rajah 2.5:", darjah_masuk_G3)
#output {id bucu, darjah masuk}

Darjah masuk Rajah 2.5: {0: 1, 1: 1, 2: 2, 3: 2, 4: 1, 5: 1}


In [16]:
#Bagi G3 (Rajah 2.5)

darjah_keluar_G3 =  dict(G3.out_degree(G3.nodes()))

nx.set_node_attributes(G3, darjah_keluar_G3, 'darjah_keluar')

print("Darjah keluar Rajah 2.5:", darjah_keluar_G3)
#output {id bucu, darjah keluar}

Darjah keluar Rajah 2.5: {0: 1, 1: 1, 2: 2, 3: 2, 4: 1, 5: 1}


In [17]:
#Bagi G3 (Rajah 2.5)

bil_bucu_G3 = G3.number_of_nodes()
jumlah_darjahmasuk_G3 = sum([d for n, d in G3.in_degree()])
jumlah_darjahkeluar_G3 = sum([d for n, d in G3.out_degree()])

purata_darjahmasuk_G3 = jumlah_darjahmasuk_G3 / float(bil_bucu_G3)
purata_darjahkeluar_G3 = jumlah_darjahkeluar_G3 / float(bil_bucu_G3)


print("Purata darjah masuk Rajah 2.5:", purata_darjahmasuk_G3)
print("Purata darjah keluar Rajah 2.5:", purata_darjahkeluar_G3)

Purata darjah masuk Rajah 2.5: 1.3333333333333333
Purata darjah keluar Rajah 2.5: 1.3333333333333333


### Taburan darjah

In [28]:
#Bagi G1 (Rajah 2.2)

df_darjah_G1 = pd.DataFrame(G1.degree(), columns=['Bucu', 'darjah'])

bil_bucu_darjah_G1 = df_darjah_G1['darjah'].value_counts().sort_index()

# Calculate the probability
p_k_G1 = bil_bucu_darjah_G1 / bil_bucu_G1

print("P_k Rajah 2.2:", p_k_G1)

#Output: k, p_k

P_k Rajah 2.2: 2    0.666667
3    0.333333
Name: darjah, dtype: float64


In [26]:
#Bagi G3 (Rajah 2.5)

df_darjah_masuk_G3 = pd.DataFrame(G3.in_degree(), columns=['Bucu', 'darjahmasuk'])
df_darjah_keluar_G3 = pd.DataFrame(G3.out_degree(), columns=['Bucu', 'darjahkeluar'])

bil_bucu_darjah_masuk_G3 = df_darjah_masuk_G3['darjahmasuk'].value_counts().sort_index()
bil_bucu_darjah_keluar_G3 = df_darjah_keluar_G3['darjahkeluar'].value_counts().sort_index()

# Calculate the probability
p_k_masuk_G3 = bil_bucu_darjah_masuk_G3 / bil_bucu_G3
p_k_keluar_G3 = bil_bucu_darjah_keluar_G3 / bil_bucu_G3

print("P_k masuk Rajah 2.5:", p_k_masuk_G3)
print("\nP_k keluar Rajah 2.5:", p_k_keluar_G3)

#Output: k, p_k

P_k masuk Rajah 2.5: 1    0.666667
2    0.333333
Name: darjahmasuk, dtype: float64

P_k keluar Rajah 2.5: 1    0.666667
2    0.333333
Name: darjahkeluar, dtype: float64


### Pemusatan kekuatan dan taburan kekuatan

In [30]:
#Bagi G2 (Rajah 2.3)

kekuatan_G2 =  dict(G2.degree(G2.nodes(),weight='weight'))

nx.set_node_attributes(G2, kekuatan_G2, 'kekuatandarjah')

print("Kekuatan Rajah 2.3:", kekuatan_G2)
#output {id bucu: darjah}

Kekuatan Rajah 2.3: {0: 3, 1: 4, 2: 6, 3: 8, 4: 6, 5: 3}


In [32]:
#Bagi G2 (Rajah 2.3)

bil_bucu_G2 = G2.number_of_nodes()
jumlah_kekuatan_G2 = sum([d for n, d in G2.degree(weight='weight')])

purata_kekuatan_G2 = jumlah_kekuatan_G2 / float(bil_bucu_G2)

print("Purata kekuatan Rajah 2.2:", purata_kekuatan_G2)

Purata kekuatan Rajah 2.2: 5.0


In [34]:
#Bagi G2 (Rajah 2.3)

df_kekuatan_G2 = pd.DataFrame(G2.degree(weight='weight'), columns=['Bucu', 'kekuatan'])

bil_bucu_kekuatan_G2 = df_kekuatan_G2['kekuatan'].value_counts().sort_index()

# Calculate the probability
p_s_G2 = bil_bucu_kekuatan_G2 / bil_bucu_G2

print("P_s Rajah 2.3:", p_s_G2)
#Output: s, p_s

P_s Rajah 2.3: 3    0.333333
4    0.166667
6    0.333333
8    0.166667
Name: kekuatan, dtype: float64


### Purata laluan terpendek

In [36]:
#Kiraan laluan terpendek untuk setiap bucu
def shortest_path(G):
    shortestpl_dict = {}
    for node in G.nodes():
        shortestpl_dict[node] = np.average(
            list(nx.shortest_path_length(G, weight=None, source=node).values()))
    return shortestpl_dict

In [37]:
#G1 (Rajah 2.2), G2 (Rajah 2.3), G3 (Rajah 2.5)

purata_laluan_terpendek_G1 = shortest_path(G1)
purata_laluan_terpendek_G2 = shortest_path(G2)
purata_laluan_terpendek_G3 = shortest_path(G3)

print("Purata laluan terpendek setiap bucu Rajah 2.2:", purata_laluan_terpendek_G1)
print("\nPurata laluan terpendek setiap bucu Rajah 2.3:", purata_laluan_terpendek_G2)
print("\nPurata laluan terpendek setiap bucu Rajah 2.5:", purata_laluan_terpendek_G3)

Purata laluan terpendek setiap bucu Rajah 2.2: {0: 1.6666666666666667, 1: 1.6666666666666667, 2: 1.1666666666666667, 3: 1.1666666666666667, 4: 1.6666666666666667, 5: 1.6666666666666667}

Purata laluan terpendek setiap bucu Rajah 2.3: {0: 1.6666666666666667, 1: 1.6666666666666667, 2: 1.1666666666666667, 3: 1.1666666666666667, 4: 1.6666666666666667, 5: 1.6666666666666667}

Purata laluan terpendek setiap bucu Rajah 2.5: {0: 2.5, 1: 2.0, 2: 1.5, 3: 1.5, 4: 2.0, 5: 2.5}


In [38]:
#G1 (Rajah 2.2), G2 (Rajah 2.3), G3 (Rajah 2.5)

global_purata_laluan_terpendek_G1 = nx.average_shortest_path_length(G1)
global_purata_laluan_terpendek_G2 = nx.average_shortest_path_length(G2)
global_purata_laluan_terpendek_G3 = nx.average_shortest_path_length(G3)

print("Purata laluan terpendek keseluruhan Rajah 2.2:", global_purata_laluan_terpendek_G1)
print("\nPurata laluan terpendek keseluruhan Rajah 2.3:", global_purata_laluan_terpendek_G2)
print("\nPurata laluan terpendek keseluruhan Rajah 2.5:", global_purata_laluan_terpendek_G3)

Purata laluan terpendek keseluruhan Rajah 2.2: 1.8

Purata laluan terpendek keseluruhan Rajah 2.3: 1.8

Purata laluan terpendek keseluruhan Rajah 2.5: 2.4


### Purata pekali pengelompokan (tidak berpemberat dan berpemberat)

In [39]:
#G1 (Rajah 2.2)
purata_pekali_pengelompokan_G1 = nx.average_clustering(G1)
print("Purata pekali pengelompokan Rajah 2.2:", purata_pekali_pengelompokan_G1)

Purata pekali pengelompokan Rajah 2.2: 0.7777777777777778


In [40]:
#G2 (Rajah 2.3)
purata_pekali_pengelompokan_berpemberat_G2 = nx.average_clustering(G2, weight='weight')
print("Purata pekali pengelompokan berpemberat Rajah 2.5:", purata_pekali_pengelompokan_berpemberat_G2)

Purata pekali pengelompokan berpemberat Rajah 2.5: 0.34877510227468606


### Transitiviti 

In [42]:
#G1 (Rajah 2.2), G2 (Rajah 2.3), G3 (Rajah 2.5)

transitiviti_G1 = nx.transitivity(G1)
transitiviti_G2 = nx.transitivity(G2)
transitiviti_G3 = nx.transitivity(G3)

print("Transitiviti Rajah 2.2:", transitiviti_G1)
print("Transitiviti Rajah 2.3:", transitiviti_G2)
print("Transitiviti Rajah 2.5:", transitiviti_G3)

Transitiviti Rajah 2.2: 0.6
Transitiviti Rajah 2.3: 0.6
Transitiviti Rajah 2.5: 0


### Pemusatan kedekatan

In [44]:
#G1 (Rajah 2.2), G2 (Rajah 2.3), G3 (Rajah 2.5)

kedekatan_G1 = nx.closeness_centrality(G1)
kedekatan_G2 = nx.closeness_centrality(G2)
kedekatan_G3 = nx.closeness_centrality(G3)

nx.set_node_attributes(G1, kedekatan_G1, 'kedekatanG1')
nx.set_node_attributes(G2, kedekatan_G2, 'kedekatanG2')
nx.set_node_attributes(G3, kedekatan_G3, 'kedekatanG3')

print("CC Rajah 2.2:", kedekatan_G1)
print("CC Rajah 2.3:", kedekatan_G2)
print("CC Rajah 2.5:", kedekatan_G3)

CC Rajah 2.2: {0: 0.5, 1: 0.5, 2: 0.7142857142857143, 3: 0.7142857142857143, 4: 0.5, 5: 0.5}
CC Rajah 2.3: {0: 0.5, 1: 0.5, 2: 0.7142857142857143, 3: 0.7142857142857143, 4: 0.5, 5: 0.5}
CC Rajah 2.5: {0: 0.4166666666666667, 1: 0.3333333333333333, 2: 0.5555555555555556, 3: 0.5555555555555556, 4: 0.3333333333333333, 5: 0.4166666666666667}


### Pemusatan pengantaraan

In [46]:
#G1 (Rajah 2.2), G2 (Rajah 2.3), G3 (Rajah 2.5)

pengantaraan_G1 = nx.betweenness_centrality(G1)
pengantaraan_G2 = nx.betweenness_centrality(G2)
pengantaraan_G3 = nx.betweenness_centrality(G3)


nx.set_node_attributes(G1, pengantaraan_G1, 'pengantaraanG1')
nx.set_node_attributes(G2, pengantaraan_G2, 'pengantaraanG2')
nx.set_node_attributes(G3, pengantaraan_G3, 'pengantaraanG3')

print("BC Rajah 2.2:", pengantaraan_G1)
print("BC Rajah 2.3:", pengantaraan_G2)
print("BC Rajah 2.5:", pengantaraan_G3)

BC Rajah 2.2: {0: 0.0, 1: 0.0, 2: 0.6000000000000001, 3: 0.6000000000000001, 4: 0.0, 5: 0.0}
BC Rajah 2.3: {0: 0.0, 1: 0.0, 2: 0.6000000000000001, 3: 0.6000000000000001, 4: 0.0, 5: 0.0}
BC Rajah 2.5: {0: 0.2, 1: 0.2, 2: 0.65, 3: 0.65, 4: 0.2, 5: 0.2}


### Pemusatan vektor eigen

In [47]:
#G1 (Rajah 2.2), G2 (Rajah 2.3), G3 (Rajah 2.5)

vektoreigen_G1 = nx.eigenvector_centrality(G1)
vektoreigen_G2 = nx.eigenvector_centrality(G2)
vektoreigen_G3 = nx.eigenvector_centrality(G3)

nx.set_node_attributes(G1, vektoreigen_G1, 'vektoreigenG1')
nx.set_node_attributes(G2, vektoreigen_G2, 'vektoreigenG2')
nx.set_node_attributes(G3, vektoreigen_G3, 'vektoreigenG3')

print("EC Rajah 2.2:", vektoreigen_G1)
print("EC Rajah 2.3:", vektoreigen_G2)
print("EC Rajah 2.5:", vektoreigen_G3)

EC Rajah 2.2: {0: 0.35355343614372076, 1: 0.35355343614372076, 2: 0.4999999355819319, 3: 0.4999999355819318, 4: 0.35355343614372065, 5: 0.35355343614372065}
EC Rajah 2.3: {0: 0.35355343614372076, 1: 0.35355343614372076, 2: 0.4999999355819319, 3: 0.4999999355819318, 4: 0.35355343614372065, 5: 0.35355343614372065}
EC Rajah 2.5: {0: 0.37198336205744653, 1: 0.25381463206079957, 2: 0.5451664983326465, 3: 0.5451664983326465, 4: 0.25381463206079957, 5: 0.37198336205744653}


### Ciri polinomial dan nilai eigen untuk Rajah 2.2


In [48]:
# Kira ciri polinomial
ciri_polinomial = np.poly(A1)
ciri_polinomial

array([ 1.00000000e+00,  7.77156117e-16, -7.00000000e+00, -4.00000000e+00,
        1.10000000e+01,  1.20000000e+01,  3.00000000e+00])

In [9]:
# Takrifkan pekali ciri polinomial
pekali = [1, 0, -7, -4, 11, 12, 3]

# Cari punca polinomial
nilai_eigen = np.roots(pekali)
nilai_eigen

array([ 2.41421356,  1.73205081, -1.73205081, -1.00000004, -0.99999996,
       -0.41421356])

In [13]:
# Nilai eigen
nilai_lambda = 2.4142

# Matrix A - lambda*I
A_lambda_I = A - nilai_lambda * np.eye(6)

# Selesaikan vektor eigen
U, S, Vh = np.linalg.svd(A_lambda_I)
# The eigenvector is the last column of Vh.T (corresponding to the smallest singular value)
vektor_eigen = Vh.T[:,-1]
vektor_eigen

array([-0.35355339, -0.35355339, -0.5       , -0.5       , -0.35355339,
       -0.35355339])

### Nilai modulariti Rajah 4.4 

In [50]:
nx.community.modularity(G1, [{0, 1, 2}, {3, 4, 5}])

0.35714285714285715

### Nilai modulariti Rajah 4. 5

In [51]:
nx.community.modularity(G1, [{0, 1, 2,3}, {4, 5}])

0.12244897959183669